In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
df['spam'] = df.Category.apply(lambda x: 0 if x == 'ham' else 1)

In [10]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [13]:
df.Message[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [14]:
df.shape

(5572, 3)

In [15]:
Message = df.Message

In [16]:
Message

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [18]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [19]:
type(Message)

pandas.core.series.Series

In [23]:
type(Message[0])

str

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [25]:
X_train.shape

(4457,)

In [26]:
X_test.shape

(1115,)

In [27]:
y_train.value_counts()

spam
0    3845
1     612
Name: count, dtype: int64

In [28]:
y_test.value_counts()

spam
0    980
1    135
Name: count, dtype: int64

In [29]:
#Create bag of words representation using CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train)

In [33]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
X_train_cv.shape

(4457, 7748)

In [35]:
v.vocabulary_

{'good': 3203,
 'afternoon': 855,
 'my': 4696,
 'love': 4246,
 'how': 3540,
 'goes': 3189,
 'that': 6810,
 'day': 2200,
 'hope': 3507,
 'maybe': 4422,
 'you': 7707,
 'got': 3217,
 'some': 6299,
 'leads': 4072,
 'on': 4962,
 'job': 3853,
 'think': 6847,
 'of': 4919,
 'boytoy': 1487,
 'and': 959,
 'send': 6021,
 'passionate': 5136,
 'kiss': 3966,
 'from': 3038,
 'across': 798,
 'the': 6814,
 'sea': 5976,
 'howz': 3547,
 'persons': 5203,
 'story': 6509,
 'still': 6485,
 'coming': 1924,
 'tonight': 6970,
 'we': 7420,
 'tried': 7043,
 'to': 6933,
 'contact': 1993,
 're': 5615,
 'your': 7712,
 'response': 5766,
 'our': 5037,
 'offer': 4926,
 'new': 4785,
 'nokia': 4828,
 'fone': 2947,
 'camcorder': 1633,
 'hit': 3461,
 'reply': 5739,
 'or': 5003,
 'call': 1614,
 '08000930705': 50,
 'for': 2960,
 'delivery': 2259,
 'no': 4819,
 'did': 2324,
 'multimedia': 4669,
 'message': 4480,
 'them': 6823,
 'mail': 4339,
 'package': 5078,
 'all': 914,
 'programs': 5477,
 'well': 7456,
 'oh': 4938,
 'after

In [36]:
X_train_np = X_train_cv.toarray()

In [37]:
np.where(X_train_np!=0)

(array([   0,    0,    0, ..., 4456, 4456, 4456], dtype=int64),
 array([ 798,  855,  959, ..., 7097, 7589, 7707], dtype=int64))

In [38]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [41]:
X_test_cv = v.transform(X_test)

In [42]:
type(X_test_cv)

scipy.sparse._csr.csr_matrix

In [43]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.96      0.96      0.96       135

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [44]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [45]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [46]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [47]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.96      0.96      0.96       135

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

